# Generated by Django 6.0.6 on 2026-07-30 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
